# Generated by Django 4.1.7 on 2023-02-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='born',
            new_name='born_date',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='location',
            new_name='born_location',
        ),
    ]
